<?php

namespace Modules\Site\Controllers;

use App\Controllers\BaseController;
use Modules\Site\Libraries\SiteSearch;

/**
 * Site-wide search.
 *
 * One box, everything behind it: courses, programmes, pages, articles,
 * resources and the faculty. A reader typing "photoshop" does not know which
 * table the answer is in and should not have to.
 *
 * noindex, always. A search results page is a page generated by whoever typed
 * into the box, and letting a crawler index an unbounded space of them is how a
 * site ends up competing with itself for its own terms.
 */
class Search extends BaseController
{
    private const PER_PAGE = 20;

    public function index(?string $locale = null)
    {
        helper(['norlanka', 'url']);

        $query = trim((string) $this->request->getGet('q'));
        $page  = max(1, (int) $this->request->getGet('page'));

        $found = ['results' => [], 'total' => 0, 'terms' => []];
        if ($query !== '') {
            $found = (new SiteSearch())->search($query, self::PER_PAGE, $page);
        }

        return view('Modules\Site\Views\search', [
            'query'           => $query,
            'results'         => $found['results'],
            'total'           => $found['total'],
            'page'            => $page,
            'perPage'         => self::PER_PAGE,
            'crumbs'          => [['label' => lang('Site.search.title')]],
            'title'           => ($query !== '' ? $query . ' — ' : '') . lang('Site.search.title') . ' — ' . setting('site_name', ''),
            'metaDescription' => lang('Site.search.meta'),
            'noIndex'         => true,
        ]);
    }
}
