<?php

namespace Modules\Admin\Controllers;

use App\Controllers\BaseController;
use Modules\Auth\Models\UserModel;

/**
 * The signed-in administrator's own account.
 *
 * This did not exist, and its absence was not a missing nicety: there was no
 * way, anywhere in the product, for an administrator to change their own
 * password. Not in the console, not on the command line. The first
 * administrator's password is generated by the seeder and printed once into the
 * deploy log — which is a build log, readable by everyone with access to the
 * repository — and the instruction that follows it, "sign in and change it",
 * pointed at a screen nobody had written. Every administrator added later would
 * have been in the same position.
 *
 * Three rules, and each is here because the obvious version of this form gets
 * one of them wrong:
 *
 *   **The current password is required.** Without it, an unattended session —
 *   a borrowed laptop, a walk to the kettle — is a permanent account takeover
 *   rather than a temporary one, because the visitor can lock the owner out.
 *
 *   **The session id is regenerated on success.** The same reasoning as at
 *   sign-in: the point of changing a password is usually that somebody else may
 *   know the old one, and a session id captured beforehand is still a way in
 *   afterwards unless it is replaced.
 *
 *   **The failures are told apart.** "Your current password is not right" and
 *   "the two new ones do not match" are different problems with different
 *   fixes, and collapsing them into "that did not work" leaves somebody
 *   retyping a password that was never the thing at fault.
 */
class Account extends BaseController
{
    /**
     * Long rather than clever.
     *
     * A composition rule — a capital, a digit, a symbol — buys very little and
     * costs a great deal: it is what produces `Password1!` on a note beside the
     * keyboard. Length is the property that actually resists guessing, and it
     * is the one a person can satisfy with a phrase they will remember.
     */
    private const MIN_LENGTH = 12;

    public function index()
    {
        helper(['norlanka', 'url']);

        return view('Modules\Admin\Views\account', [
            'title'     => 'Your account',
            'minLength' => self::MIN_LENGTH,
        ]);
    }

    public function updatePassword()
    {
        helper(['norlanka', 'url']);

        $session = session();
        $me      = $session->get('admin_user') ?? [];
        $userId  = (int) ($me['id'] ?? 0);

        if ($userId === 0) {
            return redirect()->to(site_url('admin/login'));
        }

        $users = new UserModel();
        $user  = $users->find($userId);

        if ($user === null) {
            // The account was deleted while its session was open.
            $session->remove('admin_user');

            return redirect()->to(site_url('admin/login'))->with('error', 'That account no longer exists.');
        }

        $current = (string) $this->request->getPost('current_password');
        $new     = (string) $this->request->getPost('new_password');
        $confirm = (string) $this->request->getPost('confirm_password');

        $errors = [];

        if (! password_verify($current, (string) $user['password_hash'])) {
            $errors[] = 'Your current password is not right.';
        }

        // Measured in bytes deliberately: strlen() is what a password of Sinhala
        // characters is stored and compared as, and mb_strlen() would let a
        // four-character passphrase through a twelve-character rule.
        if (strlen($new) < self::MIN_LENGTH) {
            $errors[] = 'The new password must be at least ' . self::MIN_LENGTH . ' characters.';
        }

        if ($new !== $confirm) {
            $errors[] = 'The two new passwords do not match.';
        }

        if ($new !== '' && $new === $current) {
            $errors[] = 'The new password is the same as the current one.';
        }

        // bcrypt silently truncates at 72 bytes, so anything past that is not
        // part of the password however carefully it was typed. Refused rather
        // than trimmed: a passphrase that is checked to its 72nd byte and no
        // further is not the passphrase somebody believes they set.
        if (strlen($new) > 72) {
            $errors[] = 'The new password must be 72 characters or fewer.';
        }

        if ($errors !== []) {
            return redirect()->to(site_url('admin/account'))->with('errors', $errors);
        }

        $users->update($userId, ['password_hash' => password_hash($new, PASSWORD_DEFAULT)]);

        // See the class docblock: a session id that was captured while the old
        // password was in use must not outlive it.
        $session->regenerate(true);

        return redirect()->to(site_url('admin/account'))->with('message', 'Your password has been changed.');
    }
}
