import dotData from '../../data/world-dots.json';

/**
 * Interactive global-presence map.
 *
 * The land field is painted on a <canvas> from build-time dot coordinates
 * (resources/data/world-dots.json — generated by scripts/gen-dotmap.mjs). Both
 * the dots and the HTML location markers share the exact same plate-carrée
 * projection, so markers sit precisely on the map at any width. Markers are
 * localized server-side and passed in via x-data. Fully progressive: with no
 * JS the region list still renders; the canvas is purely decorative.
 */
export default function worldMap(points = []) {
  return {
    markers: Array.isArray(points) ? points : [],
    active: null,

    init() {
      // Draw after layout is settled so getBoundingClientRect is non-zero.
      requestAnimationFrame(() => this.draw());
      this._onResize = () => this.draw();
      window.addEventListener('resize', this._onResize, { passive: true });
      // Repaint once fonts/images settle (layout can shift the stage height).
      window.addEventListener('load', this._onResize, { once: true });
    },

    destroy() {
      window.removeEventListener('resize', this._onResize);
    },

    draw() {
      const canvas = this.$refs.canvas;
      const stage = this.$refs.stage;
      if (!canvas || !stage) return;

      const w = stage.clientWidth;
      const h = stage.clientHeight;
      if (!w || !h) return;

      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      canvas.width = Math.round(w * dpr);
      canvas.height = Math.round(h * dpr);
      canvas.style.width = `${w}px`;
      canvas.style.height = `${h}px`;

      const ctx = canvas.getContext('2d');
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      ctx.clearRect(0, 0, w, h);

      // Dot radius scales gently with width; clamp so it never disappears/bloats.
      const r = Math.max(0.85, Math.min(1.9, (w / 1000) * 1.55));
      // Theme-aware: derive the land-dot colour from the foreground token so the
      // map reads correctly on the light-grey ground (dark dots) or a dark scope.
      const fg = (getComputedStyle(stage).getPropertyValue('--fg').trim() || '244 244 245')
        .split(/\s+/).join(',');
      ctx.fillStyle = `rgba(${fg},0.18)`;
      const dots = dotData.dots;
      for (let i = 0; i < dots.length; i++) {
        ctx.beginPath();
        ctx.arc(dots[i][0] * w, dots[i][1] * h, r, 0, Math.PI * 2);
        ctx.fill();
      }
    },

    // Region-list ↔ marker syncing.
    setActive(i) { this.active = i; },
    clearActive() { this.active = null; },
    isActive(i) { return this.active === i; },
  };
}
